python convert.py -src ./checkpoint/mnist/CGAN/eps1/diff_iter/DPCGAN_MNIST_eps1_iteration1000.ckpt -dest ./checkpoint/mnist/CGAN/eps1/diff_iter/DPCGAN_MNIST_eps1_iteration1000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps10/diff_iter/DPCGAN_MNIST_eps10_iteration1000.ckpt -dest ./checkpoint/mnist/CGAN/eps10/diff_iter/DPCGAN_MNIST_eps10_iteration1000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps100/diff_iter/DPCGAN_MNIST_eps100_iteration1000.ckpt -dest ./checkpoint/mnist/CGAN/eps100/diff_iter/DPCGAN_MNIST_eps100_iteration1000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps1000/diff_iter/DPCGAN_MNIST_eps1000_iteration1000.ckpt -dest ./checkpoint/mnist/CGAN/eps1000/diff_iter/DPCGAN_MNIST_eps1000_iteration1000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/epsinf/diff_iter/DPCGAN_MNIST_epsinf_iteration1000.ckpt -dest ./checkpoint/mnist/CGAN/epsinf/diff_iter/DPCGAN_MNIST_epsinf_iteration1000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps1/diff_iter/DPCGAN_MNIST_eps1_iteration5000.ckpt -dest ./checkpoint/mnist/CGAN/eps1/diff_iter/DPCGAN_MNIST_eps1_iteration5000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps10/diff_iter/DPCGAN_MNIST_eps10_iteration5000.ckpt -dest ./checkpoint/mnist/CGAN/eps10/diff_iter/DPCGAN_MNIST_eps10_iteration5000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps100/diff_iter/DPCGAN_MNIST_eps100_iteration5000.ckpt -dest ./checkpoint/mnist/CGAN/eps100/diff_iter/DPCGAN_MNIST_eps100_iteration5000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps1000/diff_iter/DPCGAN_MNIST_eps1000_iteration5000.ckpt -dest ./checkpoint/mnist/CGAN/eps1000/diff_iter/DPCGAN_MNIST_eps1000_iteration5000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/epsinf/diff_iter/DPCGAN_MNIST_epsinf_iteration5000.ckpt -dest ./checkpoint/mnist/CGAN/epsinf/diff_iter/DPCGAN_MNIST_epsinf_iteration5000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps1/diff_iter/DPCGAN_MNIST_eps1_iteration10000.ckpt -dest ./checkpoint/mnist/CGAN/eps1/diff_iter/DPCGAN_MNIST_eps1_iteration10000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps10/diff_iter/DPCGAN_MNIST_eps10_iteration10000.ckpt -dest ./checkpoint/mnist/CGAN/eps10/diff_iter/DPCGAN_MNIST_eps10_iteration10000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps100/diff_iter/DPCGAN_MNIST_eps100_iteration10000.ckpt -dest ./checkpoint/mnist/CGAN/eps100/diff_iter/DPCGAN_MNIST_eps100_iteration10000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps1000/diff_iter/DPCGAN_MNIST_eps1000_iteration10000.ckpt -dest ./checkpoint/mnist/CGAN/eps1000/diff_iter/DPCGAN_MNIST_eps1000_iteration10000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/epsinf/diff_iter/DPCGAN_MNIST_epsinf_iteration10000.ckpt -dest ./checkpoint/mnist/CGAN/epsinf/diff_iter/DPCGAN_MNIST_epsinf_iteration10000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps1/diff_iter/DPCGAN_MNIST_eps1_iteration20000.ckpt -dest ./checkpoint/mnist/CGAN/eps1/diff_iter/DPCGAN_MNIST_eps1_iteration20000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps10/diff_iter/DPCGAN_MNIST_eps10_iteration20000.ckpt -dest ./checkpoint/mnist/CGAN/eps10/diff_iter/DPCGAN_MNIST_eps10_iteration20000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps100/diff_iter/DPCGAN_MNIST_eps100_iteration20000.ckpt -dest ./checkpoint/mnist/CGAN/eps100/diff_iter/DPCGAN_MNIST_eps100_iteration20000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/eps1000/diff_iter/DPCGAN_MNIST_eps1000_iteration20000.ckpt -dest ./checkpoint/mnist/CGAN/eps1000/diff_iter/DPCGAN_MNIST_eps1000_iteration20000_.ckpt
python convert.py -src ./checkpoint/mnist/CGAN/epsinf/diff_iter/DPCGAN_MNIST_epsinf_iteration20000.ckpt -dest ./checkpoint/mnist/CGAN/epsinf/diff_iter/DPCGAN_MNIST_epsinf_iteration20000_.ckpt
