python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps1_1000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps10_1000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps100_1000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps1000_1000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_epsinf_1000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps1_5000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps10_5000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps100_5000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps1000_5000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_epsinf_5000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps1_10000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps10_10000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps100_10000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps1000_10000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_epsinf_10000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps1_20000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps10_20000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps100_20000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_eps1000_20000
python attack_models/tools/eval_roc.py --attack_type wb -ldir ./attack_models/results/wb/CGAN_epsinf_20000
